'use strict';
// Generated by scripts/gen-version.js — do not edit by hand.
// Exposes build metadata (window.__STEEMTOOLS_VERSION__) to the popup/preview UI.
window.__STEEMTOOLS_VERSION__ = {
  "version": "1.1.0",
  "date": "2026-07-14",
  "commit": "dabc1ef"
};
