#!/usr/bin/env node
'use strict';

/**
 * Generates `js/version.js`, which exposes the current build metadata to the popup
 * via `window.__STEEMTOOLS_VERSION__`.
 *
 * The metadata is the semantic version (from package.json), the build date and the
 * short git commit. On GitHub Actions the commit is taken from `GITHUB_SHA`.
 *
 * Usage: `npm run gen:version`
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const root = path.resolve(__dirname, '..');
const pkg = require(path.join(root, 'package.json'));
const outFile = path.join(root, 'js', 'version.js');

function shortCommit() {
  if (process.env.GITHUB_SHA) {
    return process.env.GITHUB_SHA.slice(0, 7);
  }
  try {
    return execSync('git rev-parse --short HEAD', {
      cwd: root,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return 'dev';
  }
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function generate() {
  const info = {
    version: pkg.version,
    date: today(),
    commit: shortCommit(),
  };
  const body =
    "'use strict';\n" +
    '// Generated by scripts/gen-version.js — do not edit by hand.\n' +
    '// Exposes build metadata (window.__STEEMTOOLS_VERSION__) to the popup UI.\n' +
    'window.__STEEMTOOLS_VERSION__ = ' +
    JSON.stringify(info, null, 2) +
    ';\n';
  fs.writeFileSync(outFile, body);
  return info;
}

if (require.main === module) {
  const info = generate();
  console.log('Wrote ' + path.relative(root, outFile) + ': ' + JSON.stringify(info));
}

module.exports = { generate, shortCommit, today };
